/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#265abb",
        "secondary-container": "#9db7fe",
        "outline-variant": "#c3c6d5",
        "secondary-fixed-dim": "#b1c5ff",
        "surface-container": "#f0edec",
        "surface-container-highest": "#e5e2e1",
        "background": "#fcf9f8",
        "tertiary": "#003372",
        "on-primary-fixed-variant": "#00419d",
        "secondary": "#425c9c",
        "on-secondary-container": "#2b4785",
        "on-secondary-fixed-variant": "#284483",
        "inverse-surface": "#313030",
        "tertiary-container": "#00499d",
        "outline": "#737784",
        "on-tertiary-fixed": "#001a41",
        "on-tertiary-container": "#9dbdff",
        "on-surface-variant": "#434652",
        "primary-fixed-dim": "#b1c5ff",
        "inverse-on-surface": "#f3f0ef",
        "inverse-primary": "#b1c5ff",
        "on-secondary": "#ffffff",
        "surface-variant": "#e5e2e1",
        "on-primary-container": "#a2bbff",
        "surface-container-high": "#ebe7e7",
        "on-error-container": "#93000a",
        "surface-bright": "#fcf9f8",
        "tertiary-fixed": "#d8e2ff",
        "on-tertiary-fixed-variant": "#004493",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "on-primary-fixed": "#001946",
        "on-surface": "#1c1b1b",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "secondary-fixed": "#dae2ff",
        "primary-container": "#0046a8",
        "on-tertiary": "#ffffff",
        "surface-dim": "#dcd9d9",
        "primary-fixed": "#d9e2ff",
        "on-background": "#1c1b1b",
        "on-secondary-fixed": "#001947",
        "surface": "#fcf9f8",
        "primary": "#00317a",
        "tertiary-fixed-dim": "#adc7ff",
        // Semantic
        "success": "#10B981",
        "warning": "#F59E0B",
        "navy": "#0B2D6B",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Pretendard", "Inter", "sans-serif"],
        body: ["Pretendard", "Inter", "sans-serif"],
        label: ["'JetBrains Mono'", "monospace"],
      },
      boxShadow: {
        'ambient': '0px 12px 32px rgba(28, 27, 27, 0.06)',
      },
    },
  },
  plugins: [],
}
